export const FETCHING_COUNT_MANAGER = "redux/fetch/FETCHING_COUNT_MANAGER";
export const FETCH_COUNT_MANAGER_SUCCESS = "redux/fetch/FETCH_COUNT_MANAGER_SUCCESS";
export const FETCH_COUNT_MANAGER_ERROR = "redux/fetch/FETCH_COUNT_MANAGER_ERROR";

export const FETCHING_COUNT_EMPLOYEE = "redux/fetch/FETCHING_COUNT_EMPLOYEE";
export const FETCH_COUNT_EMPLOYEE_SUCCESS = "redux/fetch/FETCH_COUNT_EMPLOYEE_SUCCESS";
export const FETCH_COUNT_EMPLOYEE_ERROR = "redux/fetch/FETCH_COUNT_EMPLOYEE_ERROR";

export const FETCHING_COUNT_PROCUREMENT = "redux/fetch/FETCHING_COUNT_PROCUREMENT";
export const FETCH_COUNT_PROCUREMENT_SUCCESS = "redux/fetch/FETCH_COUNT_PROCUREMENT_SUCCESS";
export const FETCH_COUNT_PROCUREMENT_ERROR = "redux/fetch/FETCH_COUNT_PROCUREMENT_ERROR";

export const FETCHING_COUNT_VENDOR = "redux/fetch/FETCHING_COUNT_VENDOR"
export const FETCHING_COUNT_VENDOR_SUCCESS = "redux/fetch/FETCHING_COUNT_VENDOR_SUCCESS"
export const FETCHING_COUNT_VENDOR_ERROR = "redux/fetch/FETCHING_COUNT_VENDOR_ERROR"